# Main Page Setup
title: Reilly Poulsen's Portfolio  

# Hero Section
name: Reilly Poulsen
headline: This is my Portfolio 
description: >- 
  A collection of my engineering projects demonstrating problem-solving, technical skills, 
  and applications of concepts from coursework and independent projects. 

# Profile image
profile_image: /assets/images/profile-image/head_shot.png

# Resume
resume-url: /assets/resume/Reilly Poulsen - Engineering Resume (2).png

# External links 
external-links:  
  linkedin: reilly-poulsen-20b0572b1   # https://www.linkedin.com/in/{url slug} 
  
# Skills Section
skills:
  - category: 3D Modeling
    tools:
    - Solidworks
    - bambu lab 

# Contact Form


# Active Theme. 
colors: 
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects

#   - vendor/ruby/
