# Main Page Setup
title: Reilly Poulsen's Portfolio  

# Hero Section
name: Reilly Poulsen
headline: Mechanical Engineering Student | CSUF 
description: >- 
      I am a hardworking third-year college student devoted to gain industry experience. 
      Seeking a challenging role within a team, bringing dedication and passion, with a proven
      track record of efficiency, successful outcomes, and effective collaboration.
      
# Profile image
profile_image: /assets/images/profile-image/head_shot.png

# Resume
resume-url: /assets/resume/Reilly Poulsen - Engineering Resume (3).png

# External links 
external-links:  
  linkedin: reilly-poulsen-20b0572b1  
  
# Skills Section
skills:
  - category: Engineering Design & Analysis
    tools:
    - SolidWorks (CAD & Assemblies)
    - AutoCAD 
    - MATLAB

  - category: Prototyping & Manufacturing
    tools:
    - FDM / 3D printing
    - Fabrication & Welding 
    - Woodworking

 - category: Electronics & Instrumentation
   tools: 
    - Circuit Analysis & Breadboarding 
    - Intermediate Wiring Harness Design 


# Active Theme. 
colors: 
  text: "#1a1c20"
  border: "#ddd"
  link: "#4a76ee"
  highlight: "#0c0cf2"
  background: "#ffffff"
  light_background: "#f3f5fb"

#########################################################################################################
# Build settings for the site. Editing the below may cause the site to malfunction.

collections:
  projects:
    output: true
    permalink: /projects/:path/


markdown: kramdown
highlighter: rouge
kramdown:
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: false
      start_line: 1
      indent: 0

plugins:
  - jekyll-feed

include:
  - _projects

#   - vendor/ruby/
